tasks:
  - init: "gp open cmake.toml
  && gp open src/example.cpp
  && cmake -Bbuild
  && cd build
  && echo Run \"make\" to build and \"./example\" to run the executable
  "

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - ms-vscode.cmake-tools@1.6.0:lvoCR5usjseB5thI3sZhWA==